# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(800, 500))
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setStyleSheet("background-color: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_6.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 2px solid rgb(0, 0, 0);\n"
"     border-radius: 6px;\n"
"    background-color:rgb(85, 0, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 16pt \"Tajawal\";\n"
"     \n"
"\n"
"     }\n"
" QPushButton:hover{\n"
"    background-color:white;\n"
"        color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(85, 0, 255);\n"
"    \n"
"     }\n"
"\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_12.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.header = QtWidgets.QLabel(self.frame_6)
        self.header.setMinimumSize(QtCore.QSize(700, 60))
        self.header.setMaximumSize(QtCore.QSize(700, 60))
        self.header.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.header.setAutoFillBackground(False)
        self.header.setStyleSheet("background-color: rgb(85, 0, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Tajawal\";\n"
"\n"
"border-radius: 30px;\n"
"\n"
"")
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.horizontalLayout_13.addWidget(self.header)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 2px solid rgb(0, 0, 0);\n"
"     border-radius: 6px;\n"
"    background-color:rgb(85, 0, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 16pt \"Tajawal\";\n"
"     \n"
"\n"
"     }\n"
" QPushButton:hover{\n"
"    background-color:white;\n"
"        color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(85, 0, 255);\n"
"    \n"
"     }\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setStyleSheet("font: 20pt \"Tajawal\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.path_prog_le = QtWidgets.QLineEdit(self.frame)
        self.path_prog_le.setMinimumSize(QtCore.QSize(0, 40))
        self.path_prog_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.path_prog_le.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.path_prog_le.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"font: 16pt \"Tajawal\";\n"
"color: rgb(41, 78, 144);")
        self.path_prog_le.setText("")
        self.path_prog_le.setMaxLength(999999999)
        self.path_prog_le.setFrame(True)
        self.path_prog_le.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.path_prog_le.setReadOnly(True)
        self.path_prog_le.setObjectName("path_prog_le")
        self.horizontalLayout.addWidget(self.path_prog_le)
        self.browse_prog_btn = QtWidgets.QPushButton(self.frame)
        self.browse_prog_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.browse_prog_btn.setMaximumSize(QtCore.QSize(180, 16777215))
        self.browse_prog_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse_prog_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.browse_prog_btn.setObjectName("browse_prog_btn")
        self.horizontalLayout.addWidget(self.browse_prog_btn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 2px solid rgb(0, 0, 0);\n"
"     border-radius: 6px;\n"
"    background-color:rgb(85, 0, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 16pt \"Tajawal\";\n"
"     \n"
"\n"
"     }\n"
" QPushButton:hover{\n"
"    background-color:white;\n"
"        color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(85, 0, 255);\n"
"    \n"
"     }\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setStyleSheet("font: 20pt \"Tajawal\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.path_files_le = QtWidgets.QLineEdit(self.frame_2)
        self.path_files_le.setMinimumSize(QtCore.QSize(0, 40))
        self.path_files_le.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.path_files_le.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.path_files_le.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(102, 102, 102);\n"
"border-radius: 6px;\n"
"font: 16pt \"Tajawal\";\n"
"color: rgb(41, 78, 144);")
        self.path_files_le.setText("")
        self.path_files_le.setMaxLength(999999999)
        self.path_files_le.setFrame(True)
        self.path_files_le.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.path_files_le.setReadOnly(True)
        self.path_files_le.setObjectName("path_files_le")
        self.horizontalLayout_4.addWidget(self.path_files_le)
        self.browse_files_btn = QtWidgets.QPushButton(self.frame_2)
        self.browse_files_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.browse_files_btn.setMaximumSize(QtCore.QSize(180, 16777215))
        self.browse_files_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse_files_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.browse_files_btn.setObjectName("browse_files_btn")
        self.horizontalLayout_4.addWidget(self.browse_files_btn)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_4.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 2px solid rgb(255, 255, 255);\n"
"     border-radius: 6px;\n"
"    background-color:none;\n"
"    color: rgb(0, 0, 0);\n"
"    font: 18pt \"Tajawal\";\n"
"     \n"
"\n"
"     }\n"
" QPushButton:hover{\n"
"    background-color:white;\n"
"        color:rgb(41, 78, 144);    \n"
"     }\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.show_chb = QtWidgets.QCheckBox(self.frame_4)
        self.show_chb.setMinimumSize(QtCore.QSize(0, 60))
        self.show_chb.setStyleSheet("font: 18pt \"Tajawal\";")
        self.show_chb.setObjectName("show_chb")
        self.horizontalLayout_9.addWidget(self.show_chb)
        self.py_convert = QtWidgets.QCheckBox(self.frame_4)
        self.py_convert.setMinimumSize(QtCore.QSize(0, 60))
        self.py_convert.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.py_convert.setStyleSheet("font: 18pt \"Tajawal\";")
        self.py_convert.setObjectName("py_convert")
        self.horizontalLayout_9.addWidget(self.py_convert)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_5.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 2px solid rgb(0, 0, 0);\n"
"     border-radius: 6px;\n"
"    background-color:rgb(85, 0, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 16pt \"Tajawal\";\n"
"     \n"
"\n"
"     }\n"
" QPushButton:hover{\n"
"    background-color:white;\n"
"        color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(85, 0, 255);\n"
"    \n"
"     }\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.create_btn = QtWidgets.QPushButton(self.frame_5)
        self.create_btn.setMinimumSize(QtCore.QSize(300, 40))
        self.create_btn.setMaximumSize(QtCore.QSize(300, 16777215))
        self.create_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.create_btn.setObjectName("create_btn")
        self.horizontalLayout_11.addWidget(self.create_btn)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(self.centralwidget)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_7.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 2px solid rgb(0, 0, 0);\n"
"     border-radius: 6px;\n"
"    background-color:rgb(85, 0, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 16pt \"Tajawal\";\n"
"     \n"
"\n"
"     }\n"
" QPushButton:hover{\n"
"    background-color:white;\n"
"        color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(85, 0, 255);\n"
"    \n"
"     }\n"
"\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.steps = QtWidgets.QLabel(self.frame_7)
        self.steps.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.steps.setStyleSheet("font: 20pt \"Tajawal\";")
        self.steps.setText("")
        self.steps.setAlignment(QtCore.Qt.AlignCenter)
        self.steps.setObjectName("steps")
        self.horizontalLayout_15.addWidget(self.steps)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_3.setStyleSheet("QPushButton {\n"
"    \n"
"    border: 2px solid rgb(0, 0, 0);\n"
"     border-radius: 6px;\n"
"    background-color:rgb(85, 0, 255);\n"
"    color:  rgb(255, 255, 255);\n"
"    font: 16pt \"Tajawal\";\n"
"     \n"
"\n"
"     }\n"
" QPushButton:hover{\n"
"    background-color:white;\n"
"        color: rgb(0, 0, 0);\n"
"border: 2px solid rgb(85, 0, 255);\n"
"    \n"
"     }\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.me = QtWidgets.QPushButton(self.frame_3)
        self.me.setMinimumSize(QtCore.QSize(350, 50))
        self.me.setMaximumSize(QtCore.QSize(350, 50))
        self.me.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.me.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.me.setStyleSheet("background-color:rgb(190, 190, 190);\n"
"border: 2px solid rgb(190, 190, 190);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Tajawal\";\n"
"border-radius: 20px;\n"
"")
        self.me.setObjectName("me")
        self.horizontalLayout_7.addWidget(self.me)
        self.me_pic = QtWidgets.QLabel(self.frame_3)
        self.me_pic.setMinimumSize(QtCore.QSize(70, 70))
        self.me_pic.setMaximumSize(QtCore.QSize(70, 70))
        self.me_pic.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.me_pic.setAutoFillBackground(False)
        self.me_pic.setStyleSheet("background-color:rgb(255,255, 255);\n"
"\n"
"font: 18pt \"Tajawal\";\n"
"\n"
"border-radius: 35px;\n"
"\n"
"\n"
"\n"
"\n"
"border: 4px solid rgb(190, 190, 190);\n"
"\n"
"")
        self.me_pic.setText("")
        self.me_pic.setScaledContents(True)
        self.me_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.me_pic.setWordWrap(False)
        self.me_pic.setObjectName("me_pic")
        self.horizontalLayout_7.addWidget(self.me_pic)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.exit_btn = QtWidgets.QPushButton(self.frame_3)
        self.exit_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.exit_btn.setMaximumSize(QtCore.QSize(180, 16777215))
        self.exit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exit_btn.setObjectName("exit_btn")
        self.horizontalLayout_7.addWidget(self.exit_btn)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addWidget(self.frame_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.browse_prog_btn, self.browse_files_btn)
        MainWindow.setTabOrder(self.browse_files_btn, self.create_btn)
        MainWindow.setTabOrder(self.create_btn, self.exit_btn)
        MainWindow.setTabOrder(self.exit_btn, self.path_prog_le)
        MainWindow.setTabOrder(self.path_prog_le, self.path_files_le)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QRC GENERATOR"))
        self.header.setText(_translate("MainWindow", "QRC GENERATOR"))
        self.label_2.setText(_translate("MainWindow", "مسار مجلد البرنامج:"))
        self.path_prog_le.setPlaceholderText(_translate("MainWindow", "مسار مجلد البرنامج"))
        self.browse_prog_btn.setText(_translate("MainWindow", "عرض"))
        self.label_3.setText(_translate("MainWindow", "مسار مجلد الملفات:"))
        self.path_files_le.setPlaceholderText(_translate("MainWindow", "مسار مجلد الملفات"))
        self.browse_files_btn.setText(_translate("MainWindow", "عرض"))
        self.show_chb.setText(_translate("MainWindow", "عرض مجلد الملف عند الإنتهاء"))
        self.py_convert.setText(_translate("MainWindow", "تحويل الملف إلى صيغة بايثون"))
        self.create_btn.setText(_translate("MainWindow", "إنشاء   "))
        self.me.setText(_translate("MainWindow", "By  Mohammed Brahmia"))
        self.exit_btn.setText(_translate("MainWindow", "خروج"))
